# Generated by rust2rpm
%bcond_without check

%global crate mockito

Name:           rust-%{crate}
Version:        0.17.0
Release:        1%{?dist}
Summary:        HTTP mocking for Rust.

License:        MIT
URL:            https://crates.io/crates/mockito
Source:         %{crates_source}

ExclusiveArch:  %{rust_arches}

BuildRequires:  rust-packaging
BuildRequires:  (crate(colored/default) >= 1.6.0 with crate(colored/default) < 2.0.0)
BuildRequires:  (crate(difference/default) >= 2.0.0 with crate(difference/default) < 3.0.0)
BuildRequires:  (crate(httparse/default) >= 1.3.3 with crate(httparse/default) < 2.0.0)
BuildRequires:  (crate(lazy_static/default) >= 1.1.0 with crate(lazy_static/default) < 2.0.0)
BuildRequires:  (crate(log/default) >= 0.4.6 with crate(log/default) < 0.5.0)
BuildRequires:  (crate(rand/default) >= 0.5.5 with crate(rand/default) < 0.6.0)
BuildRequires:  (crate(regex/default) >= 1.0.5 with crate(regex/default) < 2.0.0)
BuildRequires:  (crate(serde_json/default) >= 1.0.17 with crate(serde_json/default) < 2.0.0)

%global _description \
HTTP mocking for Rust.

%description %{_description}

%package     -n %{crate}
Summary:        %{summary}

%description -n %{crate}
%{summary}.

%files       -n %{crate}
%{_bindir}/mockito-server

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%doc README.md
%license LICENSE	
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
* Thu Apr 11 2019 Vipul Siddharth <siddharthvipul1@gmail.com> - 0.17.0-1
- Initial package
